server:
  port: 8080
  compression:
    enabled: true
  http2:
    enabled: true
  shutdown: graceful
  servlet:
    application-display-name: coop-test
    encoding:
      charset: UTF-8
      force: true

spring:
  application:
    name: coop-test
  web:
    locale: pt_BR
  mail:
    host: smtp.gmail.com
    port: 465
    username: dev@gmail.com
    password: paratestecriarsenha
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:dbcoop;
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    properties:
      hibernate:
        ddl-auto: update
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: true
        format_sql: true
    open-in-view: true
    show-sql: true
  flyway:
    enabled: true
  task:
    execution:
      thread-name-prefix: coop-tasks-
      pool:
        core-size: 2
        max-size: 50
        queue-capacity: 10000
  thymeleaf:
    mode: HTML

springdoc:
  show-actuator: false
  writer-with-default-pretty-printer: true
  swagger-ui:
    display-request-duration: false
    display-query-params: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: never

logging:
  level:
    root: info
    br.com.jj: debug

coop:
  security:
    authentication:
      jwt:
        base64-secret: MGQ0NTNhYTM5ZjM2MWFhZTNlZmVkYTQxMDE1MTRlMmVlNWE0ODI1MjY5YTYwOGExMjA5YTgxZjVjZjMwMTU1NThmNTNmNzQzOTUwMTI5ZTg1M2MzOTNjYzM3ZTU3M2Y0ODkwYWU3YWJjMzVkZmNhMjEzMWNhYjRhNTllYWI2OTI=
        token-validity-in-seconds: 86400
        token-validity-in-seconds-for-remember-me: 2592000
  email:
    remetente: noreply@coop.cf.br
